version: '2'

services:
  postgres:
    image: postgres:9.6-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=migrator_dev

